# Generated by Django 4.2.11 on 2026-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('email_mitra', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('nama_mitra', models.CharField(max_length=100)),
                ('tanggal_kerja_sama', models.DateField()),
            ],
            options={
                'verbose_name': 'Mitra',
                'verbose_name_plural': 'Mitra',
                'db_table': 'mitra',
                'managed': False,
            },
        ),
    ]
