# Generated by Django 4.2.11 on 2026-04-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hadiah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('email_mitra', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('nama_mitra', models.CharField(max_length=100)),
                ('tanggal_kerja_sama', models.DateField()),
                ('id_penyedia', models.OneToOneField(db_column='id_penyedia', on_delete=django.db.models.deletion.CASCADE, related_name='mitra', to='hadiah.penyedia')),
            ],
            options={
                'verbose_name': 'Mitra',
                'verbose_name_plural': 'Mitra',
                'db_table': 'mitra',
            },
        ),
    ]
