# Generated by Django 4.2.11 on 2026-04-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardMilesPackage',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('harga_paket', models.DecimalField(decimal_places=2, max_digits=15)),
                ('jumlah_award_miles', models.IntegerField()),
            ],
            options={
                'db_table': 'award_miles_package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bandara',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bandara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('nomor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_habis', models.DateField()),
                ('tanggal_terbit', models.DateField()),
                ('negara_penerbit', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('Paspor', 'Paspor'), ('KTP', 'KTP'), ('SIM', 'SIM')], max_length=30)),
            ],
            options={
                'db_table': 'identitas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maskapai',
            fields=[
                ('kode_maskapai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_maskapai', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'maskapai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberAwardMilesPackage',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'member_award_miles_package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=10)),
                ('first_mid_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('mobile_number', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('kewarganegaraan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pengguna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'redeem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id_tier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('minimal_frekuensi_terbang', models.IntegerField()),
                ('minimal_tier_miles', models.IntegerField()),
            ],
            options={
                'db_table': 'tier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='member', serialize=False, to='main.pengguna')),
                ('nomor_member', models.CharField(max_length=20, unique=True)),
                ('tanggal_bergabung', models.DateField()),
                ('award_miles', models.IntegerField(blank=True, null=True)),
                ('total_miles', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='staf', serialize=False, to='main.pengguna')),
                ('id_staf', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'staf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.pengguna',),
        ),
    ]
