# Generated by Django 4.2.24 on 2026-04-29 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('staf', 'Staf')], max_length=10)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=5)),
                ('first_mid_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('member_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tier', models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Blue', max_length=20, null=True)),
                ('total_miles', models.IntegerField(default=0)),
                ('award_miles', models.IntegerField(default=0)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('staf_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('kode_maskapai', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_dokumen', models.CharField(max_length=50, unique=True)),
                ('jenis', models.CharField(choices=[('Paspor', 'Paspor'), ('KTP', 'KTP'), ('SIM', 'SIM')], max_length=10)),
                ('negara_penerbit', models.CharField(max_length=50)),
                ('tanggal_terbit', models.DateField()),
                ('tanggal_habis', models.DateField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identitas', to='main.userprofile')),
            ],
        ),
    ]
