# Generated by Django 4.2.24 on 2026-04-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim_email', models.EmailField(max_length=254)),
                ('pengirim_nama', models.CharField(max_length=100)),
                ('penerima_email', models.EmailField(max_length=254)),
                ('penerima_nama', models.CharField(default='Penerima Dummy', max_length=100)),
                ('jumlah_miles', models.PositiveIntegerField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('waktu_transfer', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfer',
                'db_table': 'transfer',
                'ordering': ['-waktu_transfer'],
            },
        ),
    ]
