# Generated by Django 4.2.11 on 2026-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('jumlah', models.IntegerField()),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfer',
                'db_table': 'transfer',
                'managed': False,
            },
        ),
    ]
