# Generated by Django 4.2.24 on 2026-04-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klaim',
            fields=[
                ('no_klaim', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('maskapai', models.CharField(choices=[('GA', 'GA - Garuda Indonesia'), ('SQ', 'SQ - Singapore Airlines'), ('JT', 'JT - Lion Air'), ('QG', 'QG - Citilink'), ('ID', 'ID - Batik Air'), ('EK', 'EK - Emirates'), ('AA', 'AA - American Airlines')], max_length=5)),
                ('bandara_asal', models.CharField(choices=[('CGK', 'CGK - Soekarno-Hatta, Jakarta'), ('DPS', 'DPS - Ngurah Rai, Bali'), ('SUB', 'SUB - Juanda, Surabaya'), ('UPG', 'UPG - Sultan Hasanuddin, Makassar'), ('MDN', 'MDN - Kualanamu, Medan'), ('SIN', 'SIN - Changi, Singapore'), ('NRT', 'NRT - Narita, Tokyo'), ('KUL', 'KUL - KLIA, Kuala Lumpur'), ('SYD', 'SYD - Kingsford Smith, Sydney'), ('HKG', 'HKG - Hong Kong International')], max_length=5)),
                ('bandara_tujuan', models.CharField(choices=[('CGK', 'CGK - Soekarno-Hatta, Jakarta'), ('DPS', 'DPS - Ngurah Rai, Bali'), ('SUB', 'SUB - Juanda, Surabaya'), ('UPG', 'UPG - Sultan Hasanuddin, Makassar'), ('MDN', 'MDN - Kualanamu, Medan'), ('SIN', 'SIN - Changi, Singapore'), ('NRT', 'NRT - Narita, Tokyo'), ('KUL', 'KUL - KLIA, Kuala Lumpur'), ('SYD', 'SYD - Kingsford Smith, Sydney'), ('HKG', 'HKG - Hong Kong International')], max_length=5)),
                ('tanggal_penerbangan', models.DateField()),
                ('flight_number', models.CharField(max_length=20)),
                ('kelas_kabin', models.CharField(choices=[('Economy', 'Economy'), ('Premium Economy', 'Premium Economy'), ('Business', 'Business'), ('First', 'First')], max_length=20)),
                ('nomor_tiket', models.CharField(max_length=50)),
                ('pnr', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('email_staf', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Klaim',
                'verbose_name_plural': 'Klaim',
                'db_table': 'klaim',
                'ordering': ['-tanggal_pengajuan'],
            },
        ),
    ]
