# Generated by Django 4.2.11 on 2026-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klaim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_penerbangan', models.DateField()),
                ('flight_number', models.CharField(max_length=10)),
                ('nomor_tiket', models.CharField(max_length=20)),
                ('kelas_kabin', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=20)),
                ('pnr', models.CharField(max_length=10)),
                ('status_penerimaan', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Klaim',
                'verbose_name_plural': 'Klaim',
                'db_table': 'claim_missing_miles',
                'managed': False,
            },
        ),
    ]
