# Generated by Django 4.2.11 on 2026-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hadiah',
            fields=[
                ('kode_hadiah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('valid_start_date', models.DateField()),
                ('program_end', models.DateField()),
            ],
            options={
                'verbose_name': 'Hadiah',
                'verbose_name_plural': 'Hadiah',
                'db_table': 'hadiah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Penyedia',
                'verbose_name_plural': 'Penyedia',
                'db_table': 'penyedia',
                'managed': False,
            },
        ),
    ]
