# Generated by Django 4.2.11 on 2026-04-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Penyedia',
                'verbose_name_plural': 'Penyedia',
                'db_table': 'penyedia',
            },
        ),
        migrations.CreateModel(
            name='Hadiah',
            fields=[
                ('kode_hadiah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('valid_start_date', models.DateField()),
                ('program_end', models.DateField()),
                ('id_penyedia', models.ForeignKey(db_column='id_penyedia', on_delete=django.db.models.deletion.CASCADE, related_name='hadiah_list', to='hadiah.penyedia')),
            ],
            options={
                'verbose_name': 'Hadiah',
                'verbose_name_plural': 'Hadiah',
                'db_table': 'hadiah',
            },
        ),
    ]
